### ISSUE TITLE
Issue with caffe_unet library path

### ISSUE THREAD

**Issue by xun468** [lmb-freiburg/Unet-Segmentation#27]
So I am trying to install the U-net server according to the following tutorials 
https://lmb.informatik.uni-freiburg.de/resources/opensource/unet/#installation-backend-onsite
https://github.com/lmb-freiburg/Unet-Segmentation/wiki/Installation

on Ubuntu. When I run Fiji from the terminal I get a caffe_unet was not found error if I do not select use remote host or a cannot connect to localhost one when I do. I believe I have a library path error because when I try to run caffe from the terminal I get 

caffe: error while loading shared libraries: libcudart.so.10.0: cannot open shared object file: No such file or directory

Here is the top of my .bashrc
![image](https://user-images.githubusercontent.com/8162613/54323250-b6a54080-45f8-11e9-89ff-dbc02efdc656.png)

and here are my settings in Fiji. 
![image](https://user-images.githubusercontent.com/8162613/54323228-97a6ae80-45f8-11e9-9861-bf7f5e65a88e.png)

Can anyone see what I am doing wrong?

**Comment by ThorstenFalk** [comment]
The described problem boils down to a problem in finding your cuda 10 installation. Please check whether /usr/local/cuda actually exists and is/links to a cuda 10 installation (especially check for /usr/local/cuda/lib64/libcudart.10.0.so). If not change the path to point to your cuda 10 installation, if you have another version of cuda, download the corresponding binary package or build from scratch.

**Comment by xun468** [comment]
Thanks! It turned out to be a version mismatch between the binary and which unet version I installed.
